package frc.team2797.coremodule;

import edu.wpi.first.wpilibj.Compressor;
import edu.wpi.first.wpilibj.DoubleSolenoid;
import edu.wpi.first.wpilibj.RobotDrive;
import edu.wpi.first.wpilibj.SpeedController;
import edu.wpi.first.wpilibj.Talon;
import edu.wpi.first.wpilibj.livewindow.LiveWindow;

public class RobotMap {
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	public static SpeedController drivetraindt1;
	public static SpeedController drivetraindt2;
	public static SpeedController drivetraindt3;
	public static SpeedController drivetraindt4;
	public static RobotDrive drivetrainRobotDrive;
	public static Compressor pnArmcomp;
	public static DoubleSolenoid pnArmMain;
	public static DoubleSolenoid pnArmkicker;
	public static SpeedController shooterleftWheel;
	public static SpeedController shooterrightWheel;

	// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

	public static void init() {
		// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
		drivetraindt1 = new Talon(0);
		LiveWindow.addActuator("Drivetrain", "dt1", (Talon) drivetraindt1);

		drivetraindt2 = new Talon(1);
		LiveWindow.addActuator("Drivetrain", "dt2", (Talon) drivetraindt2);

		drivetraindt3 = new Talon(2);
		LiveWindow.addActuator("Drivetrain", "dt3", (Talon) drivetraindt3);

		drivetraindt4 = new Talon(3);
		LiveWindow.addActuator("Drivetrain", "dt4", (Talon) drivetraindt4);

		drivetrainRobotDrive = new RobotDrive(drivetraindt1, drivetraindt2, drivetraindt3, drivetraindt4);

		drivetrainRobotDrive.setSafetyEnabled(true);
		drivetrainRobotDrive.setExpiration(0.1);
		drivetrainRobotDrive.setSensitivity(0.5);
		drivetrainRobotDrive.setMaxOutput(1.0);

		pnArmcomp = new Compressor(0);

		pnArmMain = new DoubleSolenoid(0, 0, 1);
		LiveWindow.addActuator("PnArm", "main", pnArmMain);

		pnArmkicker = new DoubleSolenoid(0, 4, 5);
		LiveWindow.addActuator("PnArm", "kicker", pnArmkicker);

		shooterleftWheel = new Talon(4);
		LiveWindow.addActuator("Shooter", "leftWheel", (Talon) shooterleftWheel);

		shooterrightWheel = new Talon(5);
		LiveWindow.addActuator("Shooter", "rightWheel", (Talon) shooterrightWheel);

		// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
	}
}
